#!/usr/bin/env python3
"""
generate-registry.py -- Generate tools/plugin-registry.json from skills/*/plugin.json.

Scans each plugin package for its plugin.json definition, auto-discovers local
skills (subdirs with SKILL.md), merges cross-package includes, and outputs
the central registry used by build-plugin.py and validate-system.py.

Usage:
    python tools/generate-registry.py              # Generate registry
    python tools/generate-registry.py --dry-run    # Print to stdout, don't write
    python tools/generate-registry.py --check      # Validate plugin.json files only

No external dependencies (regex YAML parser, no PyYAML).
"""

import argparse
import json
import os
import re
import sys


# ── YAML frontmatter parsing (shared with validate-system.py) ────────────

def parse_frontmatter(content):
    """Parse YAML frontmatter from --- delimited block. Returns dict or None."""
    if not content.startswith("---"):
        return None
    parts = content.split("---", 2)
    if len(parts) < 3:
        return None
    raw = parts[1].strip()
    if not raw:
        return None

    meta = {}
    current_key = None
    current_val_lines = []

    for line in raw.split("\n"):
        # Multi-line value continuation (folded scalar >)
        if current_key and (line.startswith("  ") or line.startswith("\t")):
            current_val_lines.append(line.strip())
            continue

        # Flush previous key
        if current_key:
            meta[current_key] = " ".join(current_val_lines).strip()
            current_key = None
            current_val_lines = []

        # Key: value
        m = re.match(r'^(\S+)\s*:\s*(.*)', line)
        if m:
            key = m.group(1)
            val = m.group(2).strip()
            if val == ">" or val == "|":
                current_key = key
                current_val_lines = []
            elif val.startswith("[") and val.endswith("]"):
                items = [x.strip().strip("'\"") for x in val[1:-1].split(",") if x.strip()]
                meta[key] = items
            elif val.startswith('"') and val.endswith('"'):
                meta[key] = val[1:-1]
            elif val.startswith("'") and val.endswith("'"):
                meta[key] = val[1:-1]
            else:
                meta[key] = val

    # Flush last key
    if current_key:
        meta[current_key] = " ".join(current_val_lines).strip()

    return meta


def extract_prefix(description):
    """Extract 2-3 letter prefix from description (e.g. 'PD- Discovers...' -> 'PD')."""
    if not description:
        return ""
    m = re.match(r'^([A-Z]{2,3})-\s', description)
    return m.group(1) if m else ""


def extract_prefix_from_raw(content):
    """Fallback: extract prefix from 'prefix: XX-' in raw frontmatter text."""
    parts = content.split("---", 2)
    if len(parts) < 3:
        return ""
    raw = parts[1]
    m = re.search(r'prefix:\s*([A-Z]{2,3})-?', raw)
    return m.group(1) if m else ""


def read_skill_meta(skill_md_path):
    """Read SKILL.md and return (name, prefix) or None on failure."""
    with open(skill_md_path, "r", encoding="utf-8") as f:
        content = f.read()
    meta = parse_frontmatter(content)
    if not meta or not meta.get("name"):
        return None
    desc = meta.get("description", "")
    prefix = extract_prefix(desc)
    if not prefix:
        prefix = extract_prefix_from_raw(content)
    return {"name": meta["name"], "prefix": prefix}


def main():
    parser = argparse.ArgumentParser(description="Generate plugin-registry.json from skills/*/plugin.json")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout, don't write")
    parser.add_argument("--check", action="store_true", help="Validate plugin.json files only")
    parser.add_argument("--repo", "-r", default=None, help="Path to repo root (default: parent of tools/)")
    args = parser.parse_args()

    # Resolve repo root
    if args.repo:
        repo_root = os.path.abspath(args.repo)
    else:
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

    skills_root = os.path.join(repo_root, "skills")
    if not os.path.isdir(skills_root):
        print(f"ERROR: skills/ directory not found at {skills_root}")
        sys.exit(1)

    errors = []
    registry = {
        "_comment": "GENERATED by generate-registry.py from skills/*/plugin.json. Do not edit.",
        "plugins": {},
    }

    # Find all plugin.json files
    plugin_files = []
    for package in sorted(os.listdir(skills_root)):
        pj_path = os.path.join(skills_root, package, "plugin.json")
        if os.path.isfile(pj_path):
            plugin_files.append((package, pj_path))

    if not plugin_files:
        print("ERROR: No plugin.json files found in skills/*/")
        sys.exit(1)

    print(f"Found {len(plugin_files)} plugin definition(s)")

    for package, pj_path in plugin_files:
        with open(pj_path, "r", encoding="utf-8") as f:
            try:
                pj = json.load(f)
            except json.JSONDecodeError as e:
                errors.append(f"{pj_path}: invalid JSON: {e}")
                continue

        # Validate required fields
        missing = [field for field in ("name", "description", "version") if not pj.get(field)]
        if missing:
            errors.append(f"{pj_path}: missing required fields: {', '.join(missing)}")
            continue

        plugin_name = pj["name"]
        pkg_dir = os.path.join(skills_root, package)

        # Auto-discover local skills: subdirs with SKILL.md
        skill_entries = []
        seen_names = set()

        for subdir in sorted(os.listdir(pkg_dir)):
            subdir_path = os.path.join(pkg_dir, subdir)
            skill_md = os.path.join(subdir_path, "SKILL.md")
            if not os.path.isdir(subdir_path) or not os.path.isfile(skill_md):
                continue

            meta = read_skill_meta(skill_md)
            if meta is None:
                errors.append(f"{skill_md}: could not parse frontmatter")
                continue

            if meta["name"] in seen_names:
                errors.append(f"{plugin_name}: duplicate skill name '{meta['name']}' (local)")
                continue
            seen_names.add(meta["name"])

            skill_entries.append({
                "name": meta["name"],
                "package": package,
                "prefix": meta["prefix"],
            })

        # Merge cross-package includes
        for inc in pj.get("include", []):
            skill_dir_name = inc.get("skill", "")
            from_pkg = inc.get("from", "")
            if not skill_dir_name or not from_pkg:
                errors.append(f"{pj_path}: include entry missing 'skill' or 'from'")
                continue

            skill_md = os.path.join(skills_root, from_pkg, skill_dir_name, "SKILL.md")
            if not os.path.isfile(skill_md):
                print(f"  WARN: {plugin_name}: include '{skill_dir_name}' from '{from_pkg}' -> SKILL.md not found (placeholder, skipped)")
                continue

            meta = read_skill_meta(skill_md)
            if meta is None:
                errors.append(f"{skill_md}: could not parse frontmatter (included by {plugin_name})")
                continue

            if meta["name"] in seen_names:
                errors.append(f"{plugin_name}: duplicate skill name '{meta['name']}' (local + include)")
                continue
            seen_names.add(meta["name"])

            skill_entries.append({
                "name": meta["name"],
                "package": from_pkg,
                "prefix": meta["prefix"],
            })

        plugin_entry = {
            "description": pj["description"],
            "version": pj["version"],
        }
        if pj.get("project"):
            plugin_entry["project"] = pj["project"]
        plugin_entry["skills"] = skill_entries

        registry["plugins"][plugin_name] = plugin_entry

        skill_count = len(skill_entries)
        local_count = sum(1 for s in skill_entries if s["package"] == package)
        inc_count = skill_count - local_count
        inc_str = f" + {inc_count} included" if inc_count else ""
        print(f"  {plugin_name}: {local_count} local{inc_str} = {skill_count} skills")

    # Report errors
    if errors:
        print(f"\nERRORS ({len(errors)}):")
        for e in errors:
            print(f"  {e}")
        if args.check:
            sys.exit(1)
        # In generate mode, abort on errors too
        print("\nAborting: fix errors above before generating registry.")
        sys.exit(1)

    if args.check:
        print("\nAll plugin.json files valid.")
        sys.exit(0)

    # Output
    output = json.dumps(registry, indent=2, ensure_ascii=False) + "\n"

    if args.dry_run:
        print("\n--- Generated registry (dry-run) ---")
        print(output)
    else:
        out_path = os.path.join(repo_root, "tools", "plugin-registry.json")
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(output)
        print(f"\nRegistry written: {out_path}")
        # Count total skills
        total = sum(len(p["skills"]) for p in registry["plugins"].values())
        print(f"Total: {len(registry['plugins'])} plugins, {total} skill entries")

    sys.exit(0)


if __name__ == "__main__":
    main()
